url: "https://dulal-ramesh.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Ramesh Dulal" # the name of your site, e.g. ACME Corp.
description: "PhD Student in Economics<br><span style='color: #841617; font-family: Merriweather, serif;'>University of Oklahoma</span>"
sass:
  sass_dir: _sass
  style: compressed