menu:
- {name: 'Home', url: '/'}
- {name: 'Research', url: '/research'}
- {name: 'Teaching', url: '/teaching'}
- {name: 'CV', url: '/cv'}
- {name: 'Personal', url: '/personal'}

people:
- {name: 'Primary Investigator', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}
- {name: 'Lab Technician', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/lab-technician.jpg', url: 'lab-technician'}
- {name: 'Graduate Student', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/graduate-student.jpg', url: 'graduate-student'}

courses:
- {name: 'Vector Calculus', url: 'vector-calculus'}
- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
- {name: 'Stellar Structures', url: 'stellar-structures'}

social:
- {icon: 'github', link: 'https://github.com/Dulal-Ramesh'}
- {icon: 'twitter', link: 'https://x.com/home'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/feed/'}

contacts:
  - {department: 'Department of Economics', 
  institution: 'University of Oklahoma', 
  institution_address: '322 CCD1, 308 Cate Center Drive Norman, OK 73072', 
  email: 'ramesh.dulal@ou.edu', 
  phone: '4053265305'}       
